name: 'Replace Placeholders'
description: 'Convert the list of releases to a changelog'
author: LSVH
branding:
  icon: repeat
  color: green
inputs:
  include:
    required: false
    default: '.*'
    description: 'The file(s) where in the placeholders should be replaced'
  exclude:
    required: false
    description: 'The file(s) where in the placeholders should NOT be replaced'
  placeholders:
    required: true
    description: 'A key-value list of placeholders'
outputs:
  changed-files:
    description: 'A list of files what where changed during the replace operation'
runs:
  using: 'node12'
  main: 'dist/index.js'
